# EXAMPLE 1

In [1]:
# Libraries
from parepy_toolbox import sampling_algorithm_structural_analysis
from obj_function import nowak_collins_example

# Statement random variables
f = {
        'type': 'normal', 
        'parameters': {'mean': 40.3, 'sigma': 4.64}, 
        'stochastic variable': False, 
    }

p = {
        'type': 'gumbel max',
        'parameters': {'mean': 10.2, 'sigma': 1.12}, 
        'stochastic variable': False, 
    }

w = {
        'type': 'lognormal',
        'parameters': {'mean': 0.25, 'sigma': 0.025}, 
        'stochastic variable': False, 
    }
var = [f, p, w]

# PAREpy setup
setup = {
             'number of samples': 1000, 
             'numerical model': {'model sampling': 'mcs'}, 
             'variables settings': var, 
             'number of state limit functions or constraints': 1, 
             'none variable': None,
             'objective function': nowak_collins_example,
             'name simulation': 'nowak_collins_example',
        }

# Call algorithm
results, pf, beta = sampling_algorithm_structural_analysis(setup)

10:28:08 - Checking inputs completed!
10:28:08 - Started State Limit Function evaluation (g)...
10:28:10 - Finished State Limit Function evaluation (g) in 2.86e+00 seconds!
10:28:10 - Started evaluation beta reliability index and failure probability...
10:28:10 - Finished evaluation beta reliability index and failure probability in 3.78e-03 seconds!
10:28:10 - Voilà!!!!....simulation results are saved in nowak_collins_example_MCS_20241217-102810.txt

In [2]:
results

,X_0,X_1,X_2,R_0,S_0,G_0,I_0
0,46.736040,10.497194,0.222623,3738.883193,1865.183810,1873.699382,0.0
1,37.577144,10.593503,0.241487,3006.171486,1980.401010,1025.770476,0.0
2,35.843825,11.237702,0.227140,2867.506031,1931.513713,935.992319,0.0
3,38.604109,9.504218,0.264246,3088.328751,2054.308196,1034.020555,0.0
4,36.302757,9.494981,0.261967,2904.220586,2040.518595,863.701991,0.0
...,...,...,...,...,...,...,...
995,43.449559,10.935926,0.225589,3475.964724,1906.174220,1569.790504,0.0
996,29.005487,9.118185,0.270652,2320.438985,2070.824937,249.614048,0.0
997,43.613935,9.914726,0.240280,3489.114796,1936.708809,1552.405987,0.0
998,42.757825,12.220319,0.226400,3420.626015,1980.264249,1440.361765,0.0
999,36.535065,13.782031,0.270201,2922.805167,2320.040423,602.764745,0.0

In [3]:
pf

     I_0
0  0.002

In [4]:
beta

        I_0
0  2.878162

# EXAMPLE 2

In [5]:
# Libraries
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np

from parepy_toolbox import sampling_algorithm_structural_analysis
from obj_function import nowak_collins_time_example

# Statement random variables
f = {
        'type': 'normal', 
        'parameters': {'mean': 40.3, 'sigma': 4.64}, 
        'stochastic variable': False, 
    }

p = {
        'type': 'gumbel max',
        'parameters': {'mean': 10.2, 'sigma': 1.12}, 
        'stochastic variable': True, 
    }

w = {
        'type': 'lognormal',
        'parameters': {'mean': 0.25, 'sigma': 0.025}, 
        'stochastic variable': False, 
    }
var = [f, p, w]

# PAREpy setup
setup = {
             'number of samples': 1000, 
             'numerical model': {'model sampling': 'mcs-time', 'time steps': 5}, 
             'variables settings': var, 
             'number of state limit functions or constraints': 1, 
             'none variable': {'time analysis': list(np.linspace(0, 50, num=5, endpoint=True))},
             'objective function': nowak_collins_time_example,
             'name simulation': 'nowak_collins_time_example',
        }

# Call algorithm
results, pf, beta = sampling_algorithm_structural_analysis(setup)

10:28:10 - Checking inputs completed!
10:28:10 - Started State Limit Function evaluation (g)...
10:28:13 - Finished State Limit Function evaluation (g) in 2.79e+00 seconds!
10:28:13 - Started evaluation beta reliability index and failure probability...
10:28:13 - Finished evaluation beta reliability index and failure probability in 2.49e-02 seconds!
10:28:13 - Voilà!!!!....simulation results are saved in nowak_collins_time_example_MCS-TIME_20241217-102813.txt

In [6]:
results

,X_0_t=0,X_0_t=1,X_0_t=2,X_0_t=3,X_0_t=4,X_1_t=0,X_1_t=1,X_1_t=2,X_1_t=3,X_1_t=4,X_2_t=0,X_2_t=1,X_2_t=2,X_2_t=3,X_2_t=4,STEP_t_0,STEP_t_1,STEP_t_2,STEP_t_3,STEP_t_4,R_0_t=0,R_0_t=1,R_0_t=2,R_0_t=3,R_0_t=4,S_0_t=0,S_0_t=1,S_0_t=2,S_0_t=3,S_0_t=4,G_0_t=0,G_0_t=1,G_0_t=2,G_0_t=3,G_0_t=4,I_0_t=0,I_0_t=1,I_0_t=2,I_0_t=3,I_0_t=4
0,41.142202,41.142202,41.142202,41.142202,41.142202,12.235741,10.173257,8.686519,9.941323,9.763198,0.240121,0.240121,0.240121,0.240121,0.240121,0.0,1.0,2.0,3.0,4.0,3291.376123,3290.849503,3291.112813,3291.200583,3291.244468,2061.116919,1949.742770,1869.458898,1937.218321,1927.599596,1230.259204,1341.106733,1421.653915,1353.982262,1363.644872,0.0,0.0,0.0,0.0,0.0
1,32.942175,32.942175,32.942175,32.942175,32.942175,9.830696,9.489839,11.729464,9.651099,11.009381,0.283807,0.283807,0.283807,0.283807,0.283807,0.0,1.0,2.0,3.0,4.0,2635.373978,2634.952318,2635.163148,2635.233425,2635.268563,2186.017639,2167.611361,2288.551089,2176.319389,2249.666635,449.356340,467.340958,346.612059,458.914035,385.601928,0.0,0.0,0.0,0.0,0.0
2,42.274784,42.274784,42.274784,42.274784,42.274784,10.261789,10.095747,10.375531,8.969748,9.212388,0.231986,0.231986,0.231986,0.231986,0.231986,0.0,1.0,2.0,3.0,4.0,3381.982697,3381.441580,3381.712139,3381.802325,3381.847418,1907.077887,1898.111655,1913.219966,1837.307704,1850.410244,1474.904810,1483.329925,1468.492173,1544.494621,1531.437174,0.0,0.0,0.0,0.0,0.0
3,42.896497,42.896497,42.896497,42.896497,42.896497,9.449398,10.389926,8.882141,10.972185,9.594526,0.265486,0.265486,0.265486,0.265486,0.265486,0.0,1.0,2.0,3.0,4.0,3431.719780,3431.170705,3431.445243,3431.536755,3431.582512,2058.581825,2109.370346,2027.949952,2140.812332,2066.418706,1373.137956,1321.800360,1403.495291,1290.724423,1365.163806,0.0,0.0,0.0,0.0,0.0
4,32.450202,32.450202,32.450202,32.450202,32.450202,11.240444,10.205682,9.141289,9.959923,9.724763,0.241533,0.241533,0.241533,0.241533,0.241533,0.0,1.0,2.0,3.0,4.0,2596.016133,2595.600771,2595.808452,2595.877679,2595.912293,2015.604873,1959.727721,1902.250461,1946.456704,1933.758101,580.411261,635.873050,693.557991,649.420975,662.154192,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,42.923986,42.923986,42.923986,42.923986,42.923986,11.926022,10.273081,8.918819,8.206366,9.687039,0.255588,0.255588,0.255588,0.255588,0.255588,0.0,1.0,2.0,3.0,4.0,3433.918843,3433.369416,3433.644130,3433.735701,3433.781487,2134.593081,2045.334267,1972.204151,1933.731697,2013.687999,1299.325762,1388.035150,1461.439979,1500.004004,1420.093487,0.0,0.0,0.0,0.0,0.0
996,37.226666,37.226666,37.226666,37.226666,37.226666,10.083558,8.980058,10.112146,10.627143,9.732844,0.247586,0.247586,0.247586,0.247586,0.247586,0.0,1.0,2.0,3.0,4.0,2978.133292,2977.656791,2977.895041,2977.974458,2978.014167,1988.430992,1928.841979,1989.974726,2017.784559,1969.492416,989.702300,1048.814812,987.920315,960.189899,1008.521751,0.0,0.0,0.0,0.0,0.0
997,43.339149,43.339149,43.339149,43.339149,43.339149,10.641512,10.943814,9.939786,11.014877,10.347121,0.260322,0.260322,0.260322,0.260322,0.260322,0.0,1.0,2.0,3.0,4.0,3467.131911,3466.577170,3466.854541,3466.946998,3466.993226,2092.841683,2109.165986,2054.948495,2113.003373,2076.944599,1374.290228,1357.411184,1411.906046,1353.943625,1390.048627,0.0,0.0,0.0,0.0,0.0
998,45.979911,45.979911,45.979911,45.979911,45.979911,9.102975,10.537650,9.683686,11.143330,9.275923,0.264281,0.264281,0.264281,0.264281,0.264281,0.0,1.0,2.0,3.0,4.0,3678.392859,3677.804317,3678.098588,3678.196679,3678.245724,2032.850331,2110.322780,2064.208735,2143.029484,2042.189525,1645.542528,1567.481537,1613.889853,1535.167195,1636.056199,0.0,0.0,0.0,0.0,0.0
999,42.525867,42.525867,42.525867,42.525867,42.525867,8.842578,10.237344,9.764095,11.190322,10.928576,0.229271,0.229271,0.229271,0.229271,0.229271,0.0,1.0,2.0,3.0,4.0,3402.069398,3401.525067,3401.797233,3401.887955,3401.933315,1814.605020,1889.922402,1864.366956,1941.383208,1927.248938,1587.464378,1511.602665,1537.430277,1460.504746,1474.684378,0.0,0.0,0.0,0.0,0.0

In [7]:
pf

     G_0
0  0.001
1  0.004
2  0.004
3  0.004
4  0.004

In [8]:
beta

        G_0
0  3.090232
1  2.652070
2  2.652070
3  2.652070
4  2.652070