In [1]:
# import sys
# path = r'D:\py\parepy' # PC casa mãe wander
# path  = r'C:\git-projetos\parepy'  # PC notebook wander
# sys.path.append(path)
# from parepy_toolbox import deterministic_algorithm_structural_analysis

In [1]:
import numpy as np
import pandas as pd
from typing import Callable, Optional
import sys
sys.path.append(r'C:\Users\rezio\OneDrive\Documentos\.git codes\parepy')

from parepy_toolbox import pare as parepy
from parepy_toolbox import common_library as parepyco

In [2]:
# book e-Design Computer-Aided Engineering Design, Kuang-Hua Chang, https://www.sciencedirect.com/book/9780123820389/e-design, page 558
def obj(x):
    return 12.5 * x[0] ** 3 - x[1]

d = {'type': 'normal', 'parameters': {'mean': 1., 'std': 0.1}}
l = {'type': 'normal', 'parameters': {'mean': 10., 'std': 1.}}
var = [d, l]
x0 = [1, 10]
max_iter = 10
tol = 1E-6
r, beta = parepy.deterministic_algorithm_structural_analysis(obj, tol, max_iter, var, x0)
print(obj([0.9344699559167343, 10.200137869257235]))
print("Reliability Index (Beta):", beta)
pf = parepyco.pf_equation(beta)
print("Probability of Failure (Pf):", pf)
r

Time: 0.00s, Iteration 1 (error = 6.4413e+04)
Time: 0.00s, Iteration 2 (error = 6.4111e-02)
Time: 0.00s, Iteration 3 (error = 3.7332e-04)
Time: 0.00s, Iteration 4 (error = 1.8581e-06)
Time: 0.00s, Iteration 5 (error = 1.9277e-09)
7.993605777301127e-14
Reliability Index (Beta): 0.6851816069235225
Probability of Failure (Pf): 0.24661466445546626

,"x_0,k","x_1,k","y_0,k","y_1,k",β_k,"α_0,k","α_1,k",β_k+1,"y_0,k+1","y_1,k+1","x_0,k+1","x_1,k+1",error
0,1.000000,10.000000,0.000000,0.000000,0.000000,0.966230,-0.257680,0.644142,-0.622390,0.165982,0.937761,10.165982,6.441321e+04
1,0.937761,10.165982,-0.622390,0.165982,0.644142,0.956959,-0.290222,0.685439,-0.655937,0.198929,0.934406,10.198929,6.411113e-02
2,0.934406,10.198929,-0.655937,0.198929,0.685439,0.956378,-0.292131,0.685183,-0.655294,0.200163,0.934471,10.200163,3.733210e-04
3,0.934471,10.200163,-0.655294,0.200163,0.685183,0.956389,-0.292095,0.685182,-0.655300,0.200138,0.934470,10.200138,1.858115e-06
4,0.934470,10.200138,-0.655300,0.200138,0.685182,0.956389,-0.292095,0.685182,-0.655300,0.200138,0.934470,10.200138,1.927691e-09

In [5]:
# book Segurança estrutural: Uma introdução com aplicações à segurança, Luciano Jacinto, page 155
def obj(x):
    g, q, fy = x
    a_s = 4 * 0.79*1E-4
    return fy * a_s - 6.75 * (g + q)
g = {'type': 'normal', 'parameters': {'mean': 12., 'std': 0.05 * 12.}}
q = {'type': 'gumbel max', 'parameters': {'mean': 6., 'std': 0.10 * 6.}}
fy = {'type': 'normal', 'parameters': {'mean': 560E3, 'std': 0.05 * 560E3}}
var = [g, q, fy]
x0 = [12., 6., 560E3]
max_iter = 10
tol = 1E-6
r, beta = parepy.deterministic_algorithm_structural_analysis(obj, tol, max_iter, var, x0)
print(obj([12.744452740519371, 13.4718435600438, 560000.0]))
print("Reliability Index (Beta):", beta)
pf = parepyco.pf_equation(beta)
print("Probability of Failure (Pf):", pf)
r

-2.8801395046684775e-08
Reliability Index (Beta): 5.4227052351415
Probability of Failure (Pf): 2.9351876207358904e-08

,"x_0,k","x_1,k","x_2,k","y_0,k","y_1,k","y_2,k",β_k,"α_0,k","α_1,k","α_2,k",β_k+1,"y_0,k+1","y_1,k+1","y_2,k+1","x_0,k+1","x_1,k+1","x_2,k+1",error
0,12.000000,6.000000,560000.0,0.000000,0.177332,0.0,0.177332,-0.722775,-0.691084,0.0,10.053863,7.266679,6.948060,0.0,16.360007,9.884314,560000.0,5.569530e+01
1,16.360007,9.884314,560000.0,7.266679,3.634800,0.0,8.125047,-0.313329,-0.949645,0.0,8.110381,2.541220,7.701979,0.0,13.524732,17.264877,560000.0,1.804967e-03
2,13.524732,17.264877,560000.0,2.541220,6.607268,0.0,7.079109,-0.186984,-0.982363,0.0,5.653914,1.057192,5.554196,0.0,12.634315,13.938344,560000.0,2.013240e-01
3,12.634315,13.938344,560000.0,1.057192,5.458719,0.0,5.560150,-0.222068,-0.975031,0.0,5.427981,1.205378,5.292451,0.0,12.723227,13.500324,560000.0,2.377086e-02
4,12.723227,13.500324,560000.0,1.205378,5.289996,0.0,5.425587,-0.228380,-0.973572,0.0,5.422820,1.238461,5.279507,0.0,12.743077,13.473494,560000.0,5.100023e-04
5,12.743077,13.473494,560000.0,1.238461,5.279497,0.0,5.422811,-0.228784,-0.973477,0.0,5.422706,1.240626,5.278881,0.0,12.744376,13.471922,560000.0,1.928047e-05
6,12.744376,13.471922,560000.0,1.240626,5.278881,0.0,5.422706,-0.228807,-0.973472,0.0,5.422705,1.240755,5.278850,0.0,12.744453,13.471844,560000.0,1.269802e-07

In [ ]:
# book Structural reliability analysis and optimization: Use of approximations, Ramana Grandhi Liping Wang, page 74
def obj(x):
    x1, x2 = x
    return x1 ** 3 + x2 ** 3 - 18
x1 = {'type': 'normal', 'parameters': {'mean': 10., 'std': 5.}}
x2 = {'type': 'normal', 'parameters': {'mean': 10., 'std': 5.}}
var = [x1, x2]
x0 = [10., 10.]
max_iter = 10
tol = 1E-6
r = deterministic_algorithm_structural_analysis(obj, tol, max_iter, var, x0)
print(obj([2.0800838230984597, 2.0800838230984597]))
r

1.2086083245321788e-09

,"x_0,k","x_1,k","y_0,k","y_1,k",β_k,"α_0,k","α_1,k",β_k+1,"y_0,k+1","y_1,k+1","x_0,k+1","x_1,k+1",error
0,10.000000,10.000000,0.000000,0.000000,0.000000,0.707107,0.707107,0.933909,-0.660373,-0.660373,6.698133,6.698133,9.338989e+04
1,6.698133,6.698133,-0.660373,-0.660373,0.933909,0.707107,0.707107,1.546455,-1.093509,-1.093509,4.532454,4.532454,6.558953e-01
2,4.532454,4.532454,-1.093509,-1.093509,1.546455,0.707107,0.707107,1.932456,-1.366452,-1.366452,3.167738,3.167738,2.496031e-01
3,3.167738,3.167738,-1.366452,-1.366452,1.932456,0.707107,0.707107,2.146538,-1.517832,-1.517832,2.410842,2.410842,1.107826e-01
4,2.410842,2.410842,-1.517832,-1.517832,2.146538,0.707107,0.707107,2.227841,-1.575322,-1.575322,2.123391,2.123391,3.787655e-02
5,2.123391,2.123391,-1.575322,-1.575322,2.227841,0.707107,0.707107,2.239844,-1.583809,-1.583809,2.080957,2.080957,5.387334e-03
6,2.080957,2.080957,-1.583809,-1.583809,2.239844,0.707107,0.707107,2.240090,-1.583983,-1.583983,2.080084,2.080084,1.102522e-04
7,2.080084,2.080084,-1.583983,-1.583983,2.240090,0.707107,0.707107,2.240091,-1.583983,-1.583983,2.080084,2.080084,5.581966e-08

In [ ]:
# book Structural reliability analysis and optimization: Use of approximations, Ramana Grandhi Liping Wang, page 108
def obj1(x):
    e, i ,p = x
    return e * i - 78.12 * p
e = {'type': 'normal', 'parameters': {'mean': 2*1E7, 'std': 0.50*1E7}}
i = {'type': 'normal', 'parameters': {'mean': 1E-4, 'std': 0.2*1E-4}}
p = {'type': 'gumbel max', 'parameters': {'mean': 4., 'std': 1.}}
var = [e, i, p]
x0 = [2*1E7, 1E-4, 4.]
max_iter = 10
tol = 1E-6
r = deterministic_algorithm_structural_analysis(obj1, tol, max_iter, var, x0)
print(obj1([20000000.0, 1.9390141702046204e-05, 4.964194822163185]))
r

-6.546646392280309e-05

,"x_0,k","x_1,k","x_2,k","y_0,k","y_1,k","y_2,k",β_k,"α_0,k","α_1,k","α_2,k",β_k+1,"y_0,k+1","y_1,k+1","y_2,k+1","x_0,k+1","x_1,k+1","x_2,k+1",error
0,20000000.0,0.000100,4.000000,0.0,0.000000,0.177332,0.177332,0.0,0.982967,-0.183783,4.324272,0.0,-4.250616,0.794727,20000000.0,0.000015,4.590325,2.338524e+01
1,20000000.0,0.000015,4.590325,0.0,-4.250616,0.733871,4.313503,0.0,0.974692,-0.223552,4.170119,0.0,-4.064581,0.932240,20000000.0,0.000019,4.823253,3.324067e-02
2,20000000.0,0.000019,4.823253,0.0,-4.064581,0.925186,4.168548,0.0,0.970960,-0.239243,4.162176,0.0,-4.041305,0.995771,20000000.0,0.000019,4.912326,1.528555e-03
3,20000000.0,0.000019,4.912326,0.0,-4.041305,0.994848,4.161955,0.0,0.969443,-0.245318,4.161293,0.0,-4.034135,1.020842,20000000.0,0.000019,4.946001,1.589169e-04
4,20000000.0,0.000019,4.946001,0.0,-4.034135,1.020715,4.161262,0.0,0.968868,-0.247577,4.161176,0.0,-4.031631,1.030211,20000000.0,0.000019,4.958424,2.074797e-05
5,20000000.0,0.000019,4.958424,0.0,-4.031631,1.030194,4.161172,0.0,0.968655,-0.248409,4.161161,0.0,-4.030730,1.033669,20000000.0,0.000019,4.962986,2.702214e-06
6,20000000.0,0.000019,4.962986,0.0,-4.030730,1.033667,4.161160,0.0,0.968599,-0.248629,4.161159,0.0,-4.030493,1.034586,20000000.0,0.000019,4.964195,3.421985e-07

In [ ]:
# book Reliability of Structures, A S Nowak e K R Collins, page 124
def obj1(x):
    r, q = x
    return r - q
r = {'type': 'lognormal', 'parameters': {'mean': 200, 'std': 20}}
q = {'type': 'gumbel max', 'parameters': {'mean': 100, 'std': 12}}
var = [r, q]
x0 = [200, 100]
max_iter = 10
tol = 1E-6
r = deterministic_algorithm_structural_analysis(obj1, tol, max_iter, var, x0)
print(obj1([168.50136492096047, 168.5013661385105]))
r

-1.2175500216926594e-06

,"x_0,k","x_1,k","y_0,k","y_1,k",β_k,"α_0,k","α_1,k",β_k+1,"y_0,k+1","y_1,k+1","x_0,k+1","x_1,k+1",error
0,200.000000,100.000000,0.049876,0.177332,0.184212,0.866861,-0.498551,4.552208,-3.946129,2.269507,120.278624,124.005287,2.371179e+01
1,120.278624,124.005287,-5.047865,1.725261,5.334554,0.507197,-0.861830,5.176184,-2.625346,4.460991,149.343888,179.778434,2.968749e-02
2,149.343888,179.778434,-2.878062,3.692046,4.681287,0.375237,-0.926929,3.910652,-1.467423,3.624896,170.358540,177.307320,1.646202e-01
3,170.358540,177.307320,-1.558244,3.624345,3.945123,0.424933,-0.905225,3.770449,-1.602189,3.413104,169.611765,169.660238,4.427592e-02
4,169.611765,169.660238,-1.602285,3.407367,3.765298,0.442494,-0.896772,3.764024,-1.665556,3.375470,168.541285,168.566522,3.384666e-04
5,168.541285,168.566522,-1.665757,3.375339,3.763995,0.443171,-0.896437,3.763326,-1.667796,3.373585,168.506991,168.506892,1.776690e-04
6,168.506991,168.506892,-1.667797,3.373585,3.763326,0.443260,-0.896393,3.763328,-1.668131,3.373422,168.501365,168.501366,6.954498e-07

In [ ]:
# book Reliability of Structures, A S Nowak e K R Collins, page 129
def obj1(x):
    z, fy, m = x
    return z * fy - m
z = {'type': 'normal', 'parameters': {'mean': 100, 'std': 0.04*100}}
fy = {'type': 'lognormal', 'parameters': {'mean': 40, 'std': 0.10*40}}
m = {'type': 'gumbel max', 'parameters': {'mean': 2000, 'std': 0.10*2000}}
var = [z, fy, m] 
x0 = [100, 40, 2000]
max_iter = 10
tol = 1E-8
r = deterministic_algorithm_structural_analysis(obj1, tol, max_iter, var, x0)
print(obj1([96.64025864592539, 32.447077779125, 3135.8425558990634]))
r

-0.14856701996495758

,"x_0,k","x_1,k","x_2,k","y_0,k","y_1,k","y_2,k",β_k,"α_0,k","α_1,k","α_2,k",β_k+1,"y_0,k+1","y_1,k+1","y_2,k+1","x_0,k+1","x_1,k+1","x_2,k+1",error
0,100.000000,40.000000,2000.000000,0.000000,0.049876,0.177332,0.184212,0.345043,0.860462,-0.374902,4.495330,-1.551080,-3.868058,1.685308,93.795679,24.367232,2288.371367,23.403027
1,93.795679,24.367232,2288.371367,-1.551080,-4.918881,1.375050,5.337790,0.262364,0.619671,-0.739711,5.330088,-1.398425,-3.302901,3.942726,94.406299,28.295137,3055.738843,0.001443
2,94.406299,28.295137,3055.738843,-1.398425,-3.420649,3.218616,4.900604,0.196802,0.464758,-0.863290,4.229633,-0.832400,-1.965754,3.651399,96.670399,32.401545,3291.145907,0.136916
3,96.670399,32.401545,3291.145907,-0.832400,-2.062109,3.628802,4.255982,0.198771,0.485254,-0.851480,4.009724,-0.797018,-1.945733,3.414201,96.811926,32.777683,3161.526043,0.057862
4,96.811926,32.777683,3161.526043,-0.797018,-1.946404,3.408281,4.005010,0.210330,0.508612,-0.834910,4.023871,-0.846343,-2.046588,3.359572,96.614629,32.450118,3133.683410,0.004709
5,96.614629,32.450118,3133.683410,-0.846343,-2.047092,3.359264,4.023871,0.209916,0.509615,-0.834403,4.026265,-0.845178,-2.051845,3.359526,96.619287,32.434733,3133.831079,0.000595
6,96.619287,32.434733,3133.831079,-0.845178,-2.051846,3.359526,4.026265,0.209932,0.509412,-0.834522,4.026249,-0.845239,-2.051020,3.359995,96.619044,32.437407,3134.095976,0.000004
7,96.619044,32.437407,3134.095976,-0.845239,-2.051020,3.359995,4.026249,0.210038,0.508514,-0.835044,4.026208,-0.845656,-2.047383,3.362060,96.617378,32.449176,3135.261568,0.000010
8,96.617378,32.449176,3135.261568,-0.845656,-2.047383,3.362059,4.026208,0.209812,0.509347,-0.834592,4.026034,-0.844710,-2.050650,3.360097,96.621158,32.438602,3134.153008,0.000043
9,96.621158,32.438602,3134.153008,-0.844710,-2.050651,3.360096,4.026034,0.208617,0.508676,-0.835301,4.026200,-0.839935,-2.048031,3.363089,96.640259,32.447078,3135.842556,0.000041

In [ ]:
# book Reliability of Structures, A S Nowak e K R Collins, page 129
def obj1(x):
    z, fy, m = x
    return z * fy - m
z = {'type': 'normal', 'parameters': {'mean': 100, 'std': 0.04*100}}
fy = {'type': 'lognormal', 'parameters': {'mean': 40, 'std': 0.10*40}}
m = {'type': 'gumbel max', 'parameters': {'mean': 2000, 'std': 0.10*2000}}
var = [z, fy, m] 
x0 = [100, 40, 2000]
max_iter = 10
tol = 1E-8
r = deterministic_algorithm_structural_analysis(obj1, tol, max_iter, var, x0)
print(obj1([96.64025864592539, 32.447077779125, 3135.8425558990634]))
r

-0.14856701996495758

,"x_0,k","x_1,k","x_2,k","y_0,k","y_1,k","y_2,k",β_k,"α_0,k","α_1,k","α_2,k",β_k+1,"y_0,k+1","y_1,k+1","y_2,k+1","x_0,k+1","x_1,k+1","x_2,k+1",error
0,100.000000,40.000000,2000.000000,0.000000,0.049876,0.177332,0.184212,0.345043,0.860462,-0.374902,4.495330,-1.551080,-3.868058,1.685308,93.795679,24.367232,2288.371367,23.403027
1,93.795679,24.367232,2288.371367,-1.551080,-4.918881,1.375050,5.337790,0.262364,0.619671,-0.739711,5.330088,-1.398425,-3.302901,3.942726,94.406299,28.295137,3055.738843,0.001443
2,94.406299,28.295137,3055.738843,-1.398425,-3.420649,3.218616,4.900604,0.196802,0.464758,-0.863290,4.229633,-0.832400,-1.965754,3.651399,96.670399,32.401545,3291.145907,0.136916
3,96.670399,32.401545,3291.145907,-0.832400,-2.062109,3.628802,4.255982,0.198771,0.485254,-0.851480,4.009724,-0.797018,-1.945733,3.414201,96.811926,32.777683,3161.526043,0.057862
4,96.811926,32.777683,3161.526043,-0.797018,-1.946404,3.408281,4.005010,0.210330,0.508612,-0.834910,4.023871,-0.846343,-2.046588,3.359572,96.614629,32.450118,3133.683410,0.004709
5,96.614629,32.450118,3133.683410,-0.846343,-2.047092,3.359264,4.023871,0.209916,0.509615,-0.834403,4.026265,-0.845178,-2.051845,3.359526,96.619287,32.434733,3133.831079,0.000595
6,96.619287,32.434733,3133.831079,-0.845178,-2.051846,3.359526,4.026265,0.209932,0.509412,-0.834522,4.026249,-0.845239,-2.051020,3.359995,96.619044,32.437407,3134.095976,0.000004
7,96.619044,32.437407,3134.095976,-0.845239,-2.051020,3.359995,4.026249,0.210038,0.508514,-0.835044,4.026208,-0.845656,-2.047383,3.362060,96.617378,32.449176,3135.261568,0.000010
8,96.617378,32.449176,3135.261568,-0.845656,-2.047383,3.362059,4.026208,0.209812,0.509347,-0.834592,4.026034,-0.844710,-2.050650,3.360097,96.621158,32.438602,3134.153008,0.000043
9,96.621158,32.438602,3134.153008,-0.844710,-2.050651,3.360096,4.026034,0.208617,0.508676,-0.835301,4.026200,-0.839935,-2.048031,3.363089,96.640259,32.447078,3135.842556,0.000041

In [ ]:
# book e-Design Computer-Aided Engineering Design, Kuang-Hua Chang, https://www.sciencedirect.com/book/9780123820389/e-design, page 558
def obj(x):
    return 12.5 * x[0] ** 3 - x[1]

d = {'type': 'normal', 'parameters': {'mean': 1., 'std': 0.1}}
l = {'type': 'normal', 'parameters': {'mean': 10., 'std': 1.}}
var = [d, l]
x0 = [1, 10]
max_iter = 10
tol = 1E-6
r = deterministic_algorithm_structural_analysis(obj, tol, max_iter, var, x0, method="sorm")
# print(obj([0.9344699559167343, 10.200137869257235]))
# r