In [1]:
import sys
sys.path.append(r'C:\Users\rezio\OneDrive\Documentos\.git codes\parepy')

from parepy_toolbox import reprocess_sampling_results

In [2]:
folder = "sampling_results/"
df_all, pf_df, beta_df = reprocess_sampling_results(folder)
print("PF:", pf_df)
print("Beta:", beta_df)
df_all

PF:            Pf
G_0  0.227214
Beta:          Beta
G_0  0.748055

            X_0        X_1       G_0  I_0
0      0.902563   9.616013 -0.425451  1.0
1      1.082281  10.808151  5.038237  0.0
2      1.042979  10.467813  3.714171  0.0
3      0.946507   9.299972  1.299447  0.0
4      0.987454   8.666117  3.369282  0.0
...         ...        ...       ...  ...
12283  0.889469  10.771293 -1.974952  1.0
12284  0.935487  10.711796 -0.478315  1.0
12285  0.983658   8.110631  3.786489  0.0
12286  0.772756   9.998246 -4.230091  1.0
12287  1.018665   8.683667  4.529426  0.0

[12288 rows x 4 columns]